/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_metapatrol_jserialport_SerialPort */

#ifndef _Callbacks_com_metapatrol_jserialport_SerialPort
#define _Callbacks_com_metapatrol_jserialport_SerialPort

/*   public java.lang.String getPort(); */
#define GET_PORT_NAME "getPort"
/*   public synchronized boolean isConnected(); */
#define IS_CONNECTED_NAME "isConnected"
/*   void asyncCallback(java.lang.String, java.lang.String); */
#define ASYNC_CALLBACK_NAME "asyncCallback"
/*   static java.nio.ByteBuffer access$000(com.metapatrol.jserialport.SerialPortConnection); */
#define ACCESS$000_NAME "access$000"
/*   static java.util.Map access$200(com.metapatrol.jserialport.SerialPortConnection); */
#define ACCESS$200_NAME "access$200"
#endif //_Callbacks_com_metapatrol_jserialport_SerialPort
