/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_metapatrol_jserialport_SerialPort */

#ifndef _Included_com_metapatrol_jserialport_SerialPort
#define _Included_com_metapatrol_jserialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_metapatrol_jserialport_SerialPort
 * Method:    nativeAvailablePorts
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_metapatrol_jserialport_SerialPort_nativeAvailablePorts
  (JNIEnv *, jclass);

/*
 * Class:     com_metapatrol_jserialport_SerialPort
 * Method:    nativeConnect
 * Signature: (Ljava/lang/String;II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_metapatrol_jserialport_SerialPort_nativeConnect
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_metapatrol_jserialport_SerialPort
 * Method:    nativeDisconnect
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_metapatrol_jserialport_SerialPort_nativeDisconnect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_metapatrol_jserialport_SerialPort
 * Method:    nativeWrite
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_metapatrol_jserialport_SerialPort_nativeWrite
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_metapatrol_jserialport_SerialPort
 * Method:    nativeRead
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_metapatrol_jserialport_SerialPort_nativeRead
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
